### ISSUE TITLE
Xero\config.php

### ISSUE THREAD

**Issue by interludic** [amochohan/xerolaravel#2]
The readme.md file mentions the config file being located in the config dir. (after php artisan vendor:publish)  However i found it in "www\laravel\vendor\drawmyattention\xerolaravel\config.php" instead.

Which is correct?

**Comment by t2thec** [comment]
I'm just starting to use this myself too. I created the config manually to get it work OK. If you have it in `config/xero/config.php` it will be recognised.

When I have finished my app, I'll ask if @drawmyattention is happy for me to put through a PR so that it publishes in `config/xero.php`.

Hope that helps.

**Comment by interludic** [comment]
works in \vendor\drawmyattention\xerolaravel\config.php by default for me.
i wonder if it moves next composer update will i need to change anything, hmm... probably not
